// Pagefind is a static search lib loaded at runtime from /pagefind/pagefind.js
// It is generated by `npx pagefind` after `next build` and is not available during TS compilation.
declare module "/pagefind/pagefind.js" {
  export interface PagefindSearchResult {
    url: string;
    meta: { title?: string; [key: string]: string | undefined };
    excerpt: string;
  }
  export interface PagefindResult {
    data: () => Promise<PagefindSearchResult>;
  }
  export interface PagefindSearchResponse {
    results: PagefindResult[];
  }
  export function search(query: string): Promise<PagefindSearchResponse>;
}
