import { generateArticleText } from "../ai/provider.js";
import { buildArticlePrompt } from "../ai/prompts/article.js";
import {
  GeneratedArticleSchema,
  type GeneratedArticle,
} from "../ai/schemas/article-schema.js";
import { withRetry } from "../utils/rate-limit.js";
import type { Story } from "../utils/dedup.js";

/**
 * Classify "source richness" → target article length.
 *
 * Rationale: letting the prompt statically demand 1500+ words produces
 * hallucinated filler when the source is a two-line CVE note. Letting
 * it demand 600 words wastes depth when sources have pages of detail.
 * Adapt target to what the source actually supports.
 *
 * Signal: total chars of RSS title + excerpt across the batch.
 *   < 800 chars  → thin source  → medium article (800-1200)
 *   < 2500 chars → normal       → long (1500-2200)
 *   ≥ 2500 chars → rich source  → extended (2000-3000)
 *
 * Multi-source batches get more headroom because combined material
 * justifies more detail. Bands chosen from analysis of our 326-article
 * corpus: median source excerpt = ~1400 chars.
 */
function classifySourceRichness(stories: Story[]): {
  label: "medium" | "long" | "extended";
  targetRange: string;
  maxOutputTokens: number;
} {
  const totalSourceChars = stories.reduce(
    (sum, s) => sum + (s.title?.length ?? 0) + (s.excerpt?.length ?? 0),
    0,
  );
  if (totalSourceChars < 800) {
    return {
      label: "medium",
      targetRange: "800-1200 words",
      maxOutputTokens: 2500,
    };
  }
  if (totalSourceChars < 2500) {
    return {
      label: "long",
      targetRange: "1500-2200 words",
      maxOutputTokens: 3500,
    };
  }
  return {
    label: "extended",
    targetRange: "2000-3000 words",
    maxOutputTokens: 4500,
  };
}

/**
 * Generate a single article from 1-5 source stories.
 *
 * Returns:
 *   GeneratedArticle — success
 *   "reject"         — AI determined the story is off-topic or already covered
 *   null             — generation or parse failure
 */
export async function generateArticle(
  stories: Story[],
  recentTitles: string[] = [],
): Promise<GeneratedArticle | "reject" | null> {
  const richness = classifySourceRichness(stories);
  console.log(
    `[generate] Source richness: ${richness.label} → target ${richness.targetRange} (maxTokens=${richness.maxOutputTokens})`,
  );
  const prompt = buildArticlePrompt(stories, recentTitles, {
    targetRange: richness.targetRange,
  });

  const { text, modelUsed, paid } = await withRetry(() =>
    generateArticleText(prompt, {
      maxOutputTokens: richness.maxOutputTokens,
      temperature: 0.55,
    }),
  );

  console.log(
    `[generate] Article generated by ${modelUsed}${paid ? " (PAID)" : " (FREE)"}`,
  );

  // Strip potential markdown code fences around JSON
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    console.error(
      "[generate] JSON parse failed. Raw output:\n",
      text.slice(0, 500),
    );
    return null;
  }

  // Handle AI-level reject signal — off-topic or already-covered story
  if (
    typeof parsed === "object" &&
    parsed !== null &&
    (parsed as Record<string, unknown>).reject === true
  ) {
    const reason = (parsed as Record<string, unknown>).reason ?? "unspecified";
    console.log(`[generate] AI rejected story: ${reason}`);
    return "reject";
  }

  const result = GeneratedArticleSchema.safeParse(parsed);
  if (!result.success) {
    console.error(
      "[generate] Schema validation failed:",
      result.error.flatten(),
    );
    return null;
  }

  return result.data;
}
