import { generateArticleText } from "../ai/provider.js";
import { buildArticlePrompt } from "../ai/prompts/article.js";
import {
  GeneratedArticleSchema,
  type GeneratedArticle,
} from "../ai/schemas/article-schema.js";
import { withRetry } from "../utils/rate-limit.js";
import type { Story } from "../utils/dedup.js";

/**
 * Classify "source richness" → target article length.
 *
 * Rationale: letting the prompt statically demand 1500+ words produces
 * hallucinated filler when the source is a two-line CVE note. Letting
 * it demand 600 words wastes depth when sources have pages of detail.
 * Adapt target to what the source actually supports.
 *
 * Signal: total chars of RSS title + excerpt across the batch.
 *   < 800 chars  → thin source  → medium article (800-1200)
 *   < 2500 chars → normal       → long (1500-2200)
 *   ≥ 2500 chars → rich source  → extended (2000-3000)
 *
 * Multi-source batches get more headroom because combined material
 * justifies more detail. Bands chosen from analysis of our 326-article
 * corpus: median source excerpt = ~1400 chars.
 */
/**
 * Classify source richness by INFO DENSITY, not char length (2026-04-21
 * rewrite after Fortinet quality incident). Char-length was the wrong
 * signal — a 2500-char vendor advisory can have ZERO substantive info
 * (no CVE, no IOCs, no actors). Forcing 2000+ word articles from info-
 * poor sources pressured the LLM to pad with hedging phrases like
 * "CVE ID not yet assigned" — which shipped publicly for 6 articles.
 *
 * New signal: count concrete info tokens in source material:
 *   • CVE IDs (real, not placeholders)
 *   • CVSS scores
 *   • IOC hashes / IPs
 *   • Named threat actors (cross-referenced with known-actors list)
 * If 0 tokens present → "advisory" mode (400-700 words, reframe away
 *   from specific-vulnerability framing).
 * 1-2 tokens → medium (800-1200 words).
 * 3+ tokens → long (1500-2200 words).
 * 5+ tokens AND ≥2 sources → extended (2000-3000 words).
 */
const CVE_REGEX = /CVE-\d{4}-\d{4,}/gi;
const CVSS_REGEX =
  /CVSS(?:\s*v?[234]\.?[01]?)?\s*(?:score|of|:|=)?\s*\d+(?:\.\d+)?/gi;
const MD5_SHA_REGEX = /\b[a-fA-F0-9]{32,64}\b/g;

function countInfoTokens(stories: Story[]): number {
  let tokens = 0;
  for (const s of stories) {
    const text = `${s.title ?? ""} ${s.excerpt ?? ""}`;
    tokens += (text.match(CVE_REGEX) ?? []).length;
    tokens += (text.match(CVSS_REGEX) ?? []).length;
    tokens += (text.match(MD5_SHA_REGEX) ?? []).length;
    // Simple heuristic: count proper-noun sequences (capitalized consecutive
    // words) as potential actor/org mentions. Not perfect but directionally
    // correct — an article with "ShinyHunters" + "BlackCat" + "APT28" gets
    // 3 tokens here without needing the full known-actors list at this layer.
    tokens += (text.match(/\b(?:APT|FIN|TA)\d{1,3}\b/g) ?? []).length;
  }
  return tokens;
}

export function classifySourceRichness(stories: Story[]): {
  label: "advisory" | "medium" | "long" | "extended";
  targetRange: string;
  maxOutputTokens: number;
  infoTokens: number;
} {
  const infoTokens = countInfoTokens(stories);
  const multiSource = stories.length >= 2;

  if (infoTokens === 0) {
    // No concrete info — force advisory/summary framing. Short article
    // means LLM can't pad with hedging phrases to meet length.
    return {
      label: "advisory",
      targetRange: "400-700 words",
      maxOutputTokens: 1800,
      infoTokens,
    };
  }
  if (infoTokens <= 2) {
    return {
      label: "medium",
      targetRange: "800-1200 words",
      maxOutputTokens: 2500,
      infoTokens,
    };
  }
  if (infoTokens <= 5 || !multiSource) {
    return {
      label: "long",
      targetRange: "1500-2200 words",
      maxOutputTokens: 3500,
      infoTokens,
    };
  }
  return {
    label: "extended",
    targetRange: "2000-3000 words",
    maxOutputTokens: 4500,
    infoTokens,
  };
}

/**
 * Generate a single article from 1-5 source stories.
 *
 * Returns:
 *   GeneratedArticle — success
 *   "reject"         — AI determined the story is off-topic or already covered
 *   null             — generation or parse failure
 */
export async function generateArticle(
  stories: Story[],
  recentTitles: string[] = [],
): Promise<GeneratedArticle | "reject" | null> {
  const richness = classifySourceRichness(stories);
  console.log(
    `[generate] Source richness: ${richness.label} (${richness.infoTokens} info tokens) → target ${richness.targetRange} (maxTokens=${richness.maxOutputTokens})`,
  );
  const prompt = buildArticlePrompt(stories, recentTitles, {
    targetRange: richness.targetRange,
  });

  const { text, modelUsed, paid } = await withRetry(() =>
    generateArticleText(prompt, {
      maxOutputTokens: richness.maxOutputTokens,
      temperature: 0.55,
    }),
  );

  console.log(
    `[generate] Article generated by ${modelUsed}${paid ? " (PAID)" : " (FREE)"}`,
  );

  // Strip potential markdown code fences around JSON
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    console.error(
      "[generate] JSON parse failed. Raw output:\n",
      text.slice(0, 500),
    );
    return null;
  }

  // Handle AI-level reject signal — off-topic or already-covered story
  if (
    typeof parsed === "object" &&
    parsed !== null &&
    (parsed as Record<string, unknown>).reject === true
  ) {
    const reason = (parsed as Record<string, unknown>).reason ?? "unspecified";
    console.log(`[generate] AI rejected story: ${reason}`);
    return "reject";
  }

  const result = GeneratedArticleSchema.safeParse(parsed);
  if (!result.success) {
    console.error(
      "[generate] Schema validation failed:",
      result.error.flatten(),
    );
    return null;
  }

  return result.data;
}
