#!/usr/bin/env tsx
/**
 * Compare the live sitemap against the sitemap generated by the current repo.
 *
 * This catches stale production/edge state where deleted or moved URLs keep
 * being advertised to Google even though the current content tree no longer
 * generates them.
 */
import sitemap from "../app/sitemap.js";

interface Options {
  baseUrl: string;
  strict: boolean;
}

function parseArgs(argv: string[]): Options {
  const options: Options = {
    baseUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "https://zcybernews.com",
    strict: false,
  };

  for (const arg of argv.slice(2)) {
    if (arg === "--strict") options.strict = true;
    else if (arg.startsWith("--base-url=")) {
      options.baseUrl = arg.slice("--base-url=".length).replace(/\/+$/, "");
    }
  }

  return options;
}

function extractLocs(xml: string): string[] {
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1]!);
}

async function main() {
  const options = parseArgs(process.argv);
  const liveUrl = `${options.baseUrl}/sitemap.xml`;
  const res = await fetch(liveUrl, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (compatible; ZCyberNewsSEOAudit/1.0; +https://zcybernews.com)",
    },
  });

  if (!res.ok) {
    console.error(`[live-sitemap] ${liveUrl} returned ${res.status}`);
    process.exit(1);
  }

  const liveLocs = new Set(extractLocs(await res.text()));
  const localLocs = new Set(sitemap().map((entry) => String(entry.url)));
  const liveOnly = [...liveLocs].filter((url) => !localLocs.has(url)).sort();
  const localOnly = [...localLocs].filter((url) => !liveLocs.has(url)).sort();

  console.log(
    `[live-sitemap] live=${liveLocs.size} local=${localLocs.size} liveOnly=${liveOnly.length} localOnly=${localOnly.length}`,
  );

  if (liveOnly.length > 0) {
    console.log("\n## Live-only URLs");
    for (const url of liveOnly.slice(0, 25)) console.log(`- ${url}`);
    if (liveOnly.length > 25)
      console.log(`- ...and ${liveOnly.length - 25} more`);
  }

  if (localOnly.length > 0) {
    console.log("\n## Local-only URLs");
    for (const url of localOnly.slice(0, 25)) console.log(`- ${url}`);
    if (localOnly.length > 25)
      console.log(`- ...and ${localOnly.length - 25} more`);
  }

  if (options.strict && (liveOnly.length > 0 || localOnly.length > 0)) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
